# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "🌱 Seeding data..."
puts "Deleting old data..."

User.destroy_all
Channel.destroy_all
Post.destroy_all

u1 = User.create(username: "JessaKleine", password: "aquariousgirl", image_url: "https://images.unsplash.com/photo-1610509528015-e4c30d95a5cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", bio: "I\'m Jessa Kleine, 29-year-old clerk at a law firm who has a passion for true crime. With a background in criminal justice, I\'m fascinated by the inner workings of the criminal justice system and is always eager to learn more. In my spare time, I enjoy listening to true crime podcasts, watching the ID channel and documentaries that explore real-life criminal cases. I am also a keen observer of human behavior, and enjoys using my analytical skills to better understand the motivations behind the crimes I studied. My love for true crime has given me a unique perspective on the world, always eager to share my insights with others who share same interests. Despite the sometimes-gruesome subject matter of my hobbies, I am likewise warm and compassionate person who is always willing to lend a helping hand to those in need.", location: "San Diego CA")
u2 = User.create(username: "HanaStone", password: "taurusfly", image_url: "https://images.unsplash.com/photo-1619887806327-251c7a951dfc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDJ8fGZlbWFsZSUyMG1vZGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60", bio: "Hey Everyone! My name is Hanael Stone is a 35-year-old librarian with a passion for mystery books and justice. I love for reading books and has led me to become fascinated with shows about detectives and solving crimes. Has a keen eye for detail and enjoys using my analytical skills to solve puzzles and uncover hidden truths. I have a strong desire to help people in need and give a voice to the voiceless. Loving mother to 15-year-old daughter and 10-year-old son and enjoys spending time with family. Despite that I have a quiet demeanor, in the inside I am a strong advocate for justice and fairness, and always willing to stand up for what I believe in.", location: "Albuquerque NM")
u3 = User.create(username: "GenevieveR", password: "sagitarious", image_url: "https://images.unsplash.com/photo-1496440737103-cd596325d314?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzF8fGZlbWFsZSUyMG1vZGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60", bio: "Genevieve R. Jackson is the critically acclaimed author of Allegedly, Mondays Not Coming, and Let Me Hear a Rhyme. A Walter Dean Myers Honor Book and Coretta Scott King and John Steptoe New Talent Award winner, she received her bachelor of arts in film from Howard University, earned her master of arts in media studies from the New School, and has over a decade in TV and film experience. The Houston native still resides in the Houston Heights she loves.", location: "Houston TX")
u4 = User.create(username: "XavierV17", password: "scorpioman", image_url: "https://images.unsplash.com/photo-1528440562732-4fd65468049d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTd8fG1hbGUlMjBtb2RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=400&q=60", bio: "Xavier Anderson is a 33-year-old High School Geography Teacher with a deep passion for the outdoors, sports, and solving mysteries. In his free time, he enjoys hiking with his loyal companion, Kobe, and exploring nature. He is a natural adventurer, always seeking new challenges and experiences, and enjoys pushing his limits.", location: "Bronx NY")
u5 = User.create(username: "GiovanniLi", password: "spiderman", image_url: "https://images.unsplash.com/photo-1504593811423-6dd665756598?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzR8fG1hbGUlMjBtb2RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=400&q=60", bio: "As a science teacher, Giovanni Li is passionate about helping his students explore the world around them and gain a deeper understanding of geography. He is patient, kind, and dedicated to helping his students succeed both in and out of the classroom. His love for sports and the outdoors also translates into his teaching, as he frequently incorporates physical activity and outdoor exploration into his lesson plans.", location: "Orlando FL")
u6 = User.create(username: "ClaireJ74", password: "marvelydc", image_url: "https://images.unsplash.com/photo-1541216970279-affbfdd55aa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTB8fGZlbWFsZSUyMG1vZGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60", bio: "Claire Lopez is a professional photographer who grew up in Vancouver, Canada. As a child, she loved spending her days outdoors, playing and exploring. On rainy days, he would draw pictures of mountains and rivers. During her teen years, she discovered photography. She immediately fell in love with nature photography, and now, she has delved into writing books about mystery and novels.", location: "Winston-Salem NC")

c1 = Channel.create(name: "Unlikely Suspects", description: "A fascinating exploration of cases where the perpetrator of a murder was the last person you would expect. Join us as we unravel the stories of everyday individuals who, to the shock of their communities, were revealed to have committed heinous crimes. From upstanding citizens to model employees, we examine the clues that led investigators to the unexpected killer and uncover the shocking secrets that lay hidden beneath the surface. Don't miss out on this captivating series that will leave you questioning everything you thought you knew about crime and the people around you, only on our channel.")
c2 = Channel.create(name: "Deadly Betrayal", description: "Introducing our gripping, shocking and heart-wrenching exploration of marriages that ended in murder. Join us as we delve into the twisted and often tumultuous relationships that ended in the ultimate betrayal - the death of a partner. From the outside, these couples appeared to have it all, but behind closed doors, tensions simmered until someone snapped. We examine the warning signs that were missed, the clues that were ignored, and the explosive moments that led to fatal consequences. Don\'t miss out on this harrowing stories that will leave you questioning the true nature of love and trust, only on our channel.")
c3 = Channel.create(name: "Cold Cases: Solved and Unsolved", description: "A captivating exploration of cases that have stumped investigators for years. Join us as we take a deeper look into the details of both solved and unsolved cases, examining the forensic evidence, witness testimony, and the investigative techniques used to crack these complex cases. From notorious serial killers to elusive perpetrators, we take you on a journey through some of the most fascinating and puzzling cold cases in history.")
c4 = Channel.create(name: "Reasonable Doubt", description: "Thought-provoking exploration of cases where individuals were convicted of murder beyond reasonable doubt, but some believe they may be innocent. Committed to seeking justice for those who may have been wrongfully accused or unfairly sentenced.")
c5 = Channel.create(name: "Signs Of A Psychopath", description: "A riveting exploration into the mind of a psychopath and the heinous crimes they commit. Join us as we uncover the psychology behind some of the most notorious crimes ever committed and the twisted motives and methods of these dangerous individuals. From serial killers to mass murderers, we examine the dark side of the human psyche and shed light on the factors that drive individuals to commit such atrocities. Don\'t miss out on this chilling and thought-provoking stories, only on our channel.")
c6 = Channel.create(name: "A Crime To Remember", description: "Talks about infamous murders and crimes that took place in the US that caught a lot of media attention A true-crime series that explores some of America\'s most notorious and infamous murders, when headlines were dominated by sensational acts of violence.")

puts "✅ Done seeding!"